spring.application.name=EmployeeGraphQL


#database config
spring.datasource.url=jdbc:mysql://localhost:3306/dev
spring.datasource.username=sovon9
spring.datasource.password=password

#spring data jpa config
spring.jpa.show-sql=true

#hibernate config
spring.jpa.hibernate.ddl-auto=update

spring.graphql.graphiql.enabled=true

spring.graphql.path=/graphql
spring.graphql.websocket.path=/graphql